### PR TITLE
Structure fix

### PR DESCRIPTION
**Pull request by pilotchute**

### CODE REVIEW

**Comment by pilotchute** [comment]
Yeah, the cancel out of date jobs feature didn't seem to work, but I may not have given enough time between the settings change and my last push.

**Comment by pilotchute** [comment]
@erogluorhan The merge commit ran all checks successfully, would you be willing to accept this pull req despite the checks not running against the yapf-reformat commit?

**Comment by erogluorhan** [comment]
> @erogluorhan The merge commit ran all checks successfully, would you be willing to accept this pull req despite the checks not running against the yapf-reformat commit?

Yes, I am aware of it. If your next job is not depending on approval/merge of this PR (i.e. I don't want to make you stuck on this particular PR), please give me some time to work on this and to try to figure out if we can ensure every single commit to be CI-built (because it is an alive case of the issue we are currently having). This is because, as part of our integration workflow, we shouldn't be merging a PR without all-green CI builds, whatever the reason behind it or if the actual merge commit other than the automatic format push is passed. @clyne do you have any idea on this?

**Comment by pilotchute** [comment]
> > @erogluorhan The merge commit ran all checks successfully, would you be willing to accept this pull req despite the checks not running against the yapf-reformat commit?
> 
> Yes, I am aware of it. If your next job is not depending on approval/merge of this PR (i.e. I don't want to make you stuck on this particular PR), please give me some time to work on this and to try to figure out if we can ensure every single commit to be CI-built (because it is an alive case of the issue we are currently having). This is because, as part of our integration workflow, we shouldn't be merging a PR without all-green CI builds, whatever the reason behind it or if the actual merge commit other than the automatic format push is passed. @clyne do you have any idea on this?

I understand and accept your reasoning. This isn't something time critical, so we can use it to figure out the CI. 

Should we reach out to circleCI and see if this is a known issue?

**Comment by erogluorhan** [comment]
> Should we reach out to circleCI and see if this is a known issue?

Thanks! Indeed it sounds a great idea! Will you or should I reach out to them?

**Comment by clyne** [comment]
> > > @erogluorhan The merge commit ran all checks successfully, would you be willing to accept this pull req despite the checks not running against the yapf-reformat commit?
> > 
> > 
> > Yes, I am aware of it. If your next job is not depending on approval/merge of this PR (i.e. I don't want to make you stuck on this particular PR), please give me some time to work on this and to try to figure out if we can ensure every single commit to be CI-built (because it is an alive case of the issue we are currently having). This is because, as part of our integration workflow, we shouldn't be merging a PR without all-green CI builds, whatever the reason behind it or if the actual merge commit other than the automatic format push is passed. @clyne do you have any idea on this?
> 
> I understand and accept your reasoning. This isn't something time critical, so we can use it to figure out the CI.
> 
> Should we reach out to circleCI and see if this is a known issue?

I agree with your reasoning @erogluorhan

**Comment by clyne** [comment]
Austin is going to reach out to CircleCI to get this resolved

**Pull request merged**
