### PR TITLE
Added windows-latest to the strategy section.

### LINKED ISSUE #454: Add windows to testing matrix
Add windows to the strategy section in `.github/workflows/ci-release.yml` and `.github/workflows/ci.yml`:

```yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]
```

### PR DESCRIPTION
**Pull request by AnshRoshan**
## PR Summary

Closes #454
I have added the window-latest in the strategy section in  `.github/workflows/ci-release.yml` and `.github/workflows/ci.yml`

### CODE REVIEW

**Comment by kafitzgerald** [comment]
Shoot, it looks like the EOF tests are all failing for Windows.  

The [results seem to have the wrong sign](https://github.com/NCAR/geocat-comp/actions/runs/6131275834/job/16642482572?pr=460).  I'm not sure why this would be the case offhand though.  @anissa111 might have a better idea.

**Comment by anissa111** [comment]
Interesting! I think fixing this is probably outside the scope of this PR, but I'd like to know what's going on before merging so that we don't have our regular CI failing

**Comment by AnshRoshan** [comment]
I tried to see the error, it is generating negative from the  https://github.com/NCAR/geocat-comp/blob/36a07a414a6f673f0891429355228efa9a8e4f86/geocat/comp/stats.py#L244
  eofs = solver.eofs(neofs=neofs, eofscaling=eofscaling)
 ,then it went to xarray.py I ,in which I was not able to understand

**Comment by kafitzgerald** [comment]
Yeah, as Anissa mentioned this is not a direct result of your changes, but a separate issue (uncovered by your changes) that we'll need to sort out before we merge this.  

I'll go ahead and log another issue so we can track that separately.  Once we have that sorted out, we should *hopefully* be able to get this merged quickly.

Thanks again for your PR!

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
