### PR TITLE
VIMFC notebook

### LINKED ISSUE #292: Vertically Integrated Moisture Flux Convergence (VIMFC)
New functionality request: Vertically Integrated Moisture Flux Convergence (VIMFC)

NCL Links:
- Script: https://www.ncl.ucar.edu/Applications/Scripts/mfc_div_1.ncl
- Applications Page: https://www.ncl.ucar.edu/Applications/wind.shtml

Desired functionality:
- python equivalent of above script, both computational and plotting parts
- use above script with WRF data

image

Context: request from ESDS Event Breakout

Related NCL functions:
- [uv2dvF_Wrap](https://www.ncl.ucar.edu/Document/Functions/Contributed/uv2dvF_Wrap.shtml)
- [uv2dvF](https://www.ncl.ucar.edu/Document/Functions/Built-in/uv2dvF-1.shtml)
- [uv2dvG_Wrap](https://www.ncl.ucar.edu/Document/Functions/Contributed/uv2dvG_Wrap.shtml)
- [uv2dvG](https://www.ncl.ucar.edu/Document/Functions/Built-in/uv2dvG-1.shtml)
- [uv2dv_cfd](https://www.ncl.ucar.edu/Document/Functions/Built-in/uv2dv_cfd.shtml)

### PR DESCRIPTION
**Pull request by jukent**
## PR Summary

Closes #292 
Adds a notebook demonstrating gradient and delta pressure geocat-comp functions to calculate vertically integrated moisture flux convergence.

I might want to either make a dummy data file that we load so that the final output is consistent or continue searching for a better real dataset. 

Also this PR relies on #385 working (currently that cell fails).

Might be worth using cartopy on final contour plot (after having real data?)

## PR Checklist

**General**
- [x] Make an issue if one doesn't already exist
- [x] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [x] Add appropriate labels to this PR
- [x] Make your changes in a forked repository rather than directly in this repo
- [x] Open this PR as a draft if it is not ready for review
- [x] Convert this PR from a draft to a full PR before requesting reviewers
- [x] Request `@NCAR/geocat` for reviews
- [x] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.

**Examples**
- [x] Any new notebook examples added to `docs/examples/` folder
- [x] Pre-run all notebook cells
- [x] New notebook files added to `docs/examples.rst` toctree
- [x] New notebook files added to new entry in `docs/gallery.yml` with appropriate thumbnail photo in `docs/_static/thumbnails/`

### CODE REVIEW

**Comment by jukent** [comment]
Now using a file from geocat-datafiles. But until the next release, that file might not be recognized as in the data archive.

**Comment by jukent** [comment]
Oh that must be due to MathJax not being properly enabled. We have to do some extra things for Sphinx to understand math markdown.

**Comment by jukent** [comment]
Still not working :'(

**Comment by philipc2** [comment]
> This looks great, sorry for the slow review! There's just one small thing I would like to see addressed before I approve.
> 
> It looks like some of the functions aren't rendering properly on the docs: image
> 
> I don't know what could be causing this, ping me if you can't figure it out fairly quickly and I can take a look, too!

I was getting a similar issue when working on a usage example notebook for UXarray.

**Comment by jukent** [comment]
Progress! from doing math blocks like {math}'' instead of using $$
Screen Shot 2023-05-17 at 12 53 11 PM
Not sure why the first equation is right justified though. I have one thing to try on that.

**Comment by jukent** [comment]
It's left justified now! and rendering math equations right

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
