### PR TITLE
pre-commit hook for codespell

### LINKED ISSUE #578: Add codespell to pre-commit hooks
**Describe the bug**
codespell catches common spelling mistakes and would be useful as part of the pre-commit hooks

**Expected behavior**
Current codespell report for comp:

```
./geocat/comp/interpolation.py:168: temepratures ==> temperatures
./geocat/comp/meteorology.py:645: funtion ==> function
./geocat/comp/climatologies.py:130: allias ==> alias
./geocat/comp/fourier_filters.py:18: freqency ==> frequency
./geocat/comp/fourier_filters.py:177: allowes ==> allows, allowed
./geocat/comp/fourier_filters.py:178: freqency ==> frequency
./geocat/comp/fourier_filters.py:211: allowes ==> allows, allowed
./geocat/comp/fourier_filters.py:212: freqency ==> frequency
./geocat/comp/fourier_filters.py:246: allowes ==> allows, allowed
./geocat/comp/fourier_filters.py:247: freqency ==> frequency
./geocat/comp/fourier_filters.py:285: allowes ==> allows, allowed
./geocat/comp/fourier_filters.py:286: freqency ==> frequency
./docs/installation.rst:45: envionment ==> environment
./docs/getting-started.rst:20: aquainted ==> acquainted
./docs/examples/fourier_filter.ipynb:39: hight ==> height, high
./docs/examples/fourier_filter.ipynb:167: ploting ==> plotting
./docs/examples/fourier_filter.ipynb:249: hight ==> height, high
./docs/examples/fourier_filter.ipynb:249: enviromental ==> environmental
./docs/examples/fourier_filter.ipynb:290: simultaniously ==> simultaneously
./docs/examples/vimfc.ipynb:44: componenets ==> components
./docs/examples/vimfc.ipynb:494: componenet ==> component
./docs/examples/vimfc.ipynb:1140: fo ==> of, for, to, do, go
./docs/examples/climatology_average.ipynb:74: COO ==> COUP
./docs/examples/climatology_average.ipynb:110: argments ==> arguments
./docs/examples/climatology_average.ipynb:159: yeilds ==> yields
./docs/user_api/index.rst:42: Iterpolation ==> Interpolation
```
Jargon that can be configured to ignore
```
./geocat/comp/interpolation.py:231: alph ==> alpha
./geocat/comp/interpolation.py:234: alph ==> alpha
./geocat/comp/interpolation.py:234: alph ==> alpha
./geocat/comp/interpolation.py:240: alph ==> alpha
./geocat/comp/climatologies.py:235: OND ==> ONE, AND
./geocat/comp/climatologies.py:284: OND ==> ONE, AND
./geocat/comp/climatologies.py:486: OND ==> ONE, AND
./geocat/comp/climatologies.py:546: OND ==> ONE, AND
./docs/examples/fourier_filter.ipynb:178: Te ==> The, Be, We, To
./docs/examples/fourier_filter.ipynb:178: bu ==> by, be, but, bug, bun, bud, buy, bum
./docs/examples/fourier_filter.ipynb:217: eDN ==> end
./docs/examples/fourier_filter.ipynb:217: aLo ==> also
./docs/examples/fourier_filter.ipynb:301: Ptd ==> Pdf
./docs/examples/fourier_filter.ipynb:301: te ==> the, be, we, to
./docs/examples/fourier_filter.ipynb:353: bU ==> by, be, but, bug, bun, bud, buy, bum
./docs/examples/fourier_filter.ipynb:353: Ot ==> To, Of, Or, Not
./docs/examples/fourier_filter.ipynb:353: Fo ==> Of, For, To, Do, Go
./docs/examples/fourier_filter.ipynb:353: te ==> the, be, we, to
./docs/examples/fourier_filter.ipynb:353: fO ==> of, for, to, do, go
./docs/examples/calendar_average.ipynb:71: tE ==> the, be, we, to
./docs/examples/calendar_average.ipynb:122: te ==> the, be, we, to
./docs/examples/calendar_average.ipynb:205: fO ==> of, for, to, do, go
./docs/examples/vimfc.ipynb:1140: DeD ==> dead
```

### PR DESCRIPTION
**Pull request by cyschneck**
## PR Summary

Closes #578

## PR Checklist

**General**
- [x] Make an issue if one doesn't already exist
- [x] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [x] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the next unreleased release. Possible sections include: Documentation, New Features, Bug Fixes, Internal Changes, Breaking Changes/Deprecated
- [x] Add appropriate labels to this PR
- [x] Make your changes in a forked repository rather than directly in this repo
- [x] Open this PR as a draft if it is not ready for review
- [x] Convert this PR from a draft to a full PR before requesting reviewers
- [x] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.
- [x] If needed, squash and merge PR commits into a single commit to clean up commit history

### CODE REVIEW

**Comment by anissa111** [comment]
This seems reasonable, but I have one discussion point. The rest of our pre-commits use `--in-place` or `-w` flags, so that they fix everything automatically on commit locally. Should we also use the `-w` flag here? 

I could see either side, either updating it to match the behavior of the pre-commits or leaving it to manual correction to prevent unexpected changes of purposeful non-standard spellings.

**Comment by cyschneck** [comment]
I think current/future work will probably include some jargon specific words that automatically changing will cause unexpected errors once committed that could be confusing to try and fix after the fact. yapf auto formatting isn't likely to impact behavior but changing a word in a string or variable name could. I included an update in the contributing guide about how to handle jargon words to pass this pre-commit stage

**Review by kafitzgerald — APPROVED** [review]
Thanks for adding this!  Looks good to me and happy to adapt to edge cases as we go if need be.

**Comment by anissa111** [comment]
> I think current/future work will probably include some jargon specific words that automatically changing will cause unexpected errors once committed that could be confusing to try and fix after the fact. yapf auto formatting isn't likely to impact behavior but changing a word in a string or variable name could. I included an update in the contributing guide about how to handle jargon words to pass this pre-commit stage

Sounds good to me!

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
