### PR TITLE
Relhum function on GPU using CuPy

### PR DESCRIPTION
**Pull request by haniyeka**
geocat_cupy.yml: Created an export from the geocat Conda environment, including the required packages.

meteorology.py: The Relhum function and its helper functions _relhum, and _xrelhum are ported to do the computation on GPU using CuPy. They have a new input variable, "use_gpu", which its default value is set to "False", but when the user sets it to "True", the computation of the Relhum function will be done on GPU.

test_meteorology.py: The Test_Relhum class is changed according to the changes in meteolorogy.py. They also have a new input variable, the "use_gpu", which is set to "False" by default.

Note: The current ported version works on a single GPU device, but the next step is to try running the function on multiple GPUs.

### CODE REVIEW

**Comment by erogluorhan** [comment]
@haniyeka Thanks very much for putting this together! I will give it a review as soon as I have time.

**Comment by erogluorhan** [comment]
@haniyeka did you have a chance to explore the lightweight [cupy-xarray](https://github.com/xarray-contrib/cupy-xarray) interface during this work?

**Comment by haniyeka** [comment]
> @haniyeka did you have a chance to explore the lightweight [cupy-xarray](https://github.com/xarray-contrib/cupy-xarray) interface during this work?

Hi Orhan, 
Actually, I investigated this package first weeks of the summer, and the reason that I didn't used it is that the package is in "Experimental" phase. So, I implemented the code by converting the numpy array inside xarray to cupy. 

https://github.com/haniyeka/geocat_test_scripts/blob/main/smalltests/xarray-cupy-v2.ipynb

**Comment by dcherian** [comment]
> package is in "Experimental" phase.

This just means it needs someone talented (like you!) to step in and contribute =)

**Comment by haniyeka** [comment]
> > package is in "Experimental" phase.
> 
> This just means it needs someone talented (like you!) to step in and contribute =)

Hi! I am willing! How can I be part of this? Can you add me to the repo?

**Comment by haniyeka** [comment]
> > package is in "Experimental" phase.
> 
> This just means it needs someone talented (like you!) to step in and contribute =)

**Comment by dcherian** [comment]
> Hi! I am willing! How can I be part of this? Can you add me to the repo?

Great! The only thing to do is to contribute when and where you can.

For example, given your work here, are there other helper functions that would be useful in that repo? If so, please open an issue there to discuss.

I wrote some quick [docs](https://cupy-xarray.readthedocs.io/quickstart.html). Is there something else that you think would be useful to demonstrate there?

**Pull request closed without merging**
