### PR TITLE
Fix Python version in upstream CI

### LINKED ISSUE #435: Upstream-dev CI failing after 3.11 update
**Describe the bug**
Upstream-dev CI is now failing (sooner than it used to) after the 3.11 update. 
https://github.com/NCAR/geocat-comp/actions/runs/5481409328/jobs/9985673211 

It looks like the conda installs after the upstream dependency installation mess up the environment.  I think it's because the actions workflow config file has Python set to 3.10 and then conda updates it to 3.11 (specified as Python >=3.9 in the conda env file) which removes the upstream dependencies, but not entirely sure.  

Sounds like @philipc2 is seeing something similar over on UXarray and said he'd let us know if he gets to fixing this before us.  It came up earlier today during team time.

### PR DESCRIPTION
**Pull request by philipc2**
## PR Summary
Remove Python from upstream dev CI environment file so it does unintentionally update to the latest version and break things.
Closes #435

## PR Checklist

**General**
- [x] Make an issue if one doesn't already exist
- [x] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [x] Add a brief summary of changes to `docs/release-notes.rst`
- [x] Add appropriate labels to this PR
- [x] Make your changes in a forked repository rather than directly in this repo
- [x] Open this PR as a draft if it is not ready for review
- [x] Convert this PR from a draft to a full PR before requesting reviewers
- [x] Request `@NCAR/geocat` for reviews
- [x] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.

### CODE REVIEW

**Comment by philipc2** [comment]
@kafitzgerald 

https://github.com/NCAR/geocat-comp/actions/runs/5490783568

It's no longer failing due to missing dependencies after this change, however it's still generally failing due to other reasons (the ones you mentioned that were unrelated to this issue)

**Comment by anissa111** [comment]
See manually triggered upstream actions run here: https://github.com/NCAR/geocat-comp/actions/runs/6660041805

**Comment by kafitzgerald** [comment]
> See manually triggered upstream actions run here: https://github.com/NCAR/geocat-comp/actions/runs/6660041805

Yeah, hopefully this helps that situation, but it certainly won't get things passing (upstream CI was failing before the issue this addresses).  Maybe this makes things more clear though w/ the other failures.  

I'm by no committed to get this merged on its own - just was trying to remove one layer from the problem or show how to (since we got that far once).

**Comment by anissa111** [comment]
> > See manually triggered upstream actions run here: [NCAR/geocat-comp/actions/runs/6660041805](https://github.com/NCAR/geocat-comp/actions/runs/6660041805)
> 
> Yeah, hopefully this helps that situation, but it certainly won't get things passing (upstream CI was failing before the issue this addresses because of #381). Maybe this makes things more clear though w/ the other failures.
> 
> I'm by no committed to get this merged on its own - just was trying to remove one layer from the problem or show how to (since we got that far once). I'll leave that call to you @anissa111.
> 
> Let me know if you'd like me to look into / help with this more @cyschneck / @anissa111 otherwise I was planning to just leave this here for now.
> 
> And looks like we are back to the failure from #381 (so it's working as intended).

Ah, let's just get it merged, one less thing to deal with later!

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
