### PR TITLE
Update to conda-build badge link

### LINKED ISSUE #247: Is "Conda Build" badage actually needed?

### PR DESCRIPTION
**Pull request by marodrig**
Instead of updating the link used for the conda-build badge, the upstream-dev-ci workflow is now used.

resolve #247

### CODE REVIEW

**Review by erogluorhan — COMMENTED** [review]
What is the intention with using `upstream-dev-ci,yml` workflow in place of Conda builds?  (cc: @anissa111 )

**Comment by anissa111** [comment]
@erogluorhan thanks for the ping! I agree, but I think that the wording on the badge might be confusing. 

@marodrig, I see your comment that both badges had distinct valuable info, but I'm not quite clear how they're that much different

**Comment by erogluorhan** [comment]
> @erogluorhan thanks for the ping! I agree, but I think that the wording on the badge might be confusing.
> 
> @marodrig, I see your comment that both badges had distinct valuable info, but I'm not quite clear how they're that much different

I think, in the past, we had such a test ("conda build") to actually test if our repo-specific conda recipes were working. As we transferred that to conda-forge and we longer have "build tests", as well as we already have a badge that shows our latest conda release, I think we should better rename this badge to something like "Upstream CI" have whatever Mario put here.

Thoughts?

**Comment by anissa111** [comment]
> I think, in the past, we had such a test ("conda build") to actually test if our repo-specific conda recipes were working. As we transferred that to conda-forge and we longer have "build tests", as well as we already have a badge that shows our latest conda release, I think we should better rename this badge to something like "Upstream CI" and have whatever Mario put here.
>
> Thoughts?

I think that's good! Especially since we'll be adding to the upstream ci (hopefully) next iteration.

**Comment by marodrig** [comment]
@erogluorhan @anissa111 I change the name of the badge to Upstream CI.

**Comment by erogluorhan** [comment]
> @erogluorhan @anissa111 I change the name of the badge to Upstream CI.

Looks good except please fix the sizing issue:

image

**Review by erogluorhan — CHANGES_REQUESTED** [review]
Looks good except please fix the sizing issue (and green colors look all different, if that can be fixed, too):

image

**Comment by marodrig** [comment]
Screen Shot 2022-11-08 at 3 32 09 PM
@erogluorhan I updated the width, and the color to a more uniform look.

**Review by erogluorhan — APPROVED** [review]
Great

**Comment by erogluorhan** [comment]
> It seems like this was closed, but now merged.

I still see the older badge in the `main` branch, you may need to reopen and merge this PR.

**Pull request merged**
