### PR TITLE
Add autoupdate for pre-commit hook versions

### LINKED ISSUE #603: Refresh pre-commit hook versions
Refresh the pre-commit hooks to recent versions to maintain compatibility and account for bug fixes/updates introduced in recent updates

```
https://github.com/google/yapf
v0.33.0 -> v0.42.2
```
```
https://github.com/myint/docformatter
v1.4 -> v1.7.5
```
```
https://github.com/pre-commit/pre-commit-hooks
v3.4.0 -> v4.5.0
```

### PR DESCRIPTION
**Pull request by cyschneck**
## PR Summary

Closes #603 

## PR Checklist

**General**
- [x] Make an issue if one doesn't already exist
- [x] Link the issue this PR resolves by adding `closes #XXX` to the PR description where XXX is the number of the issue.
- [x] Add a brief summary of changes to `docs/release-notes.rst` in a relevant section for the next unreleased release. Possible sections include: Documentation, New Features, Bug Fixes, Internal Changes, Breaking Changes/Deprecated
- [x] Add appropriate labels to this PR
- [x] Make your changes in a forked repository rather than directly in this repo
- [x] Open this PR as a draft if it is not ready for review
- [x] Convert this PR from a draft to a full PR before requesting reviewers
- [x] Passes `precommit`. To set up on your local, run `pre-commit install` from the top level of the repository. To manually run pre-commits, use `pre-commit run --all-files` and re-add any changed files before committing again and pushing.
- [x] If needed, squash and merge PR commits into a single commit to clean up commit history

### CODE REVIEW

**Comment by cyschneck** [comment]
Is the `meta.yaml` file still being used in this repo? I didn't see it, but it is referenced in the pre-commit
```
-   repo: https://github.com/pre-commit/pre-commit-hooks    # Some common pre-commit hooks
    rev: v4.6.0
    hooks:
    - id: check-yaml               # Checks the syntax of .yaml files.
      args: [--allow-multiple-documents]
      exclude: 'meta.yaml'    # Exclude this because it gives an error for '%' in Line 1 and couldn't fix yet
    - id: end-of-file-fixer        # Makes sure files end with a newline.
    - id: trailing-whitespace      # Checks for any tabs or spaces after the last non-whitespace character on the line.
- id: check-docstring-first # Checks that code comes after the docstrings.
```

**Comment by anissa111** [comment]
> @anissa111 is the `meta.yaml` file still being used in this repo? I didn't see it, but it is referenced in the pre-commit
> 
> ```
> -   repo: https://github.com/pre-commit/pre-commit-hooks    # Some common pre-commit hooks
>     rev: v4.6.0
>     hooks:
>     - id: check-yaml               # Checks the syntax of .yaml files.
>       args: [--allow-multiple-documents]
>       exclude: 'meta.yaml'    # Exclude this because it gives an error for '%' in Line 1 and couldn't fix yet
>     - id: end-of-file-fixer        # Makes sure files end with a newline.
>     - id: trailing-whitespace      # Checks for any tabs or spaces after the last non-whitespace character on the line.
> - id: check-docstring-first # Checks that code comes after the docstrings.
> ```

Ah, yeah, nope! At one time, we did use a `meta.yaml`, but that line must have lingered after we refactored the packaging.

**Comment by cyschneck** [comment]
As part of this refresh I'll remove it

**Comment by anissa111** [comment]
I'm also kind of suprised that we didn't have this set up to autoupdate. I assumed dependabot was doing something like this, but apparently that's not something dependabot is set up to do. 

I think we should consider setting up pre-commit.ci. I'm not sure if that's actually doable with the github org structure/permissions, but it's worth looking into. 

We could also theoretically just add a ``pre-commit autoupdate`` push somewhere in our CI [as suggested here](https://chrisholdgraf.com/blog/2022/precommit-autoupdate/) if pre-commit.ci isn't possible.

**Comment by cyschneck** [comment]
Will do. I'll update it to include the autoupdate-r

**Review by anissa111 — COMMENTED** [review]
So I was a bit worried about just adding the ci step there because I didn't know if we could use pre-commit.ci, but a number of other NCAR repos are already doing so!

I've added geocat-comp to pre-commit.ci, which should allow the changes here to work as expected.

See the additional action run in this test PR: https://github.com/NCAR/geocat-comp/pull/605

image

**Comment by anissa111** [comment]
With this, we should remove the github action based pre-commit check.

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
